### PR TITLE
Add an option to setup a shadow to the tabs' container

### PR DESCRIPTION
**Pull request by Remi-B**
Add an option to setup a shadow to the tabs' container. This option is
an Optional struct witch contains Optional values to setup the shadow
in the view.layer. By default the behaviour stay unchanged.

All values are optionals so we can set only some values and let the
others as default from the UIKit.

### CODE REVIEW

**Comment by Remi-B** [comment]
It adds a convenience way of adding a shadow to the tab bar. It can actually be done by iterating through the viewPager’s subviews to find the ScrollView, but I think this can be a cleaner an safer way of doing it.

`for view in viewPager.view.subviews {
            guard let tabsView = view as? UIScrollView else {
                return
            }
            
            tabsView.clipsToBounds = false
            tabsView.layer.shadowColor = UIColor.black.cgColor
            tabsView.layer.shadowOpacity = 0.6
            tabsView.layer.shadowRadius = 4
            viewPager.view.bringSubview(toFront: tabsView)
        }`

**Comment by nrlnishan** [comment]
Hi @Remi-B ,

I am having trouble setting the path property, while setting the shadowOptions property.  Since TabContainer itself is a private variable, there wouldn't be any way to get its path unless you compute it manually. 

Can you check it out once & see if changes are to be made and submit pull request again?

Thanks :)

**Comment by Remi-B** [comment]
Hi @nrlnishan,

I didn't realise that the path property wasn't easy to use. I made some changes to allow setting the tabs bounds as shadowPath, this can now be set using a simple flag and the path is created internally.

I did let the option to set a different path computed manually but if the **useBoundsShadowPath** flag is set to **true** the path is ignored so their won't be conflict.

I also added an example implementation in the MainViewController.

Let me know if it's no ok for you ;)

**Comment by nrlnishan** [comment]
Hi @Remi-B ,

On a quick inspection, it seems that the width of the shadow doesnot extends fully to the end of the tab container content size. Can you check it out once? 

Screenshot

Thanks

**Comment by Remi-B** [comment]
Hi @nrlnishan,

Sorry I didn't saw this issue. It seems the issue was because the path was set before all tabs are added. 

I trier to move the code that apply the shadowPath after the scrollView's contentSize has been set but it doesn't really fix the problem, the shadow does extend under the whole tabContainer but it doesn't extends under the scrollView's 'bouncing ' area. (see the attached picture)
image-1

Has the main goal of the shadow path property is to make the shadow's frame static and not dynamic, it seems that this property doesn't really make sense for a scrollView that can extends its bounds.

I think we should just remove that shadowPath option. Let me know if it's Ok for you, and I will commit these changes.

PS: An other solution wold be to embed the scrollView inside a container view (Or to add a view below the scrollView). So the shadow would be applied to that container instead of to the scrollView. But I don't think this is a really good option.

**Comment by nrlnishan** [comment]
I think we should remove the properties `path` & `useBoundsShadowPath` altogether & implicitly define the shadow path.  In normal cases the path for the shadow is always the path drawn from its bounds. 

And the path should be set once the tabs are added. That's when the contentsize changes. So setting the path in viewDidLayoutSubviews() fixes the size issue of shadow. 

And the BezierPath is not being created properly using the bounds of tabView. So providing the height & width of CGRect explicitly, i.e height = tabContainer.height & width = tabContainer.contentSize.width creates the perfect shadow path. 

Can you check it out once and submit pull request again? Or i will be looking into this whenever i have time & do it in next update.

**Comment by Remi-B** [comment]
I don't really understand what you meant by 

> we should remove the properties path & useBoundsShadowPath altogether & implicitly define the shadow path.

Do you want to always use the view's bound as shadow path ?

**Comment by nrlnishan** [comment]
I am currently refactoring this library in **development** branch. The way by which tab container was created previous is changed in this refactor. As a result adding of Shadow is now possible. Thus closing this PR.

For further contribution, please create a PR on development Branch

**Pull request closed without merging**
